version: '3.8'

services:
  cookies:
    build: ./cookies
    container_name: cookies
    restart: always
    expose:
      - "8000"
    networks:
      - app-network

  intercept:
    build: ./intercept
    container_name: intercept
    restart: always
    expose:
      - "8000"
    networks:
      - app-network

  whoisstudent:
    build: ./whoisstudent
    container_name: whoisstudent
    restart: always
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/wildcard.crt:/etc/ssl/certs/wildcard.crt
      - /etc/ssl/private/wildcard.key:/etc/ssl/private/wildcard.key
      - ./incl-files:/usr/share/nginx/html/incl-files
      - ./1984:/usr/share/nginx/html/1984
    depends_on:
      - cookies
      - intercept
      - whoisstudent
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
